export const menuItems: FoodItem[] = [
    {
      id: 1,
      title: "Grilled Chicken Salad",
      description: "Fresh greens topped with grilled chicken and a light vinaigrette.",
      image: "https://www.eatingbirdfood.com/wp-content/uploads/2023/06/grilled-chicken-salad-hero.jpg",
      ingredients: ["Chicken", "Lettuce", "Tomatoes", "Vinaigrette", "Cucumber"],
    },
    {
      id: 2,
      title: "Margherita Pizza",
      description: "Classic pizza with fresh mozzarella, tomatoes, and basil.",
      image: "https://cdn.shopify.com/s/files/1/0274/9503/9079/files/20220211142754-margherita-9920_5a73220e-4a1a-4d33-b38f-26e98e3cd986.jpg?v=1723650067",
      ingredients: ["Pizza Dough", "Tomatoes", "Mozzarella", "Basil"],
    },
    {
      id: 3,
      title: "Spaghetti Carbonara",
      description: "Rich and creamy pasta with pancetta and parmesan.",
      image: "https://www.allrecipes.com/thmb/a_0W8yk_LLCtH-VPqg2uLD9I5Pk=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/11973-spaghetti-carbonara-ii-DDMFS-4x3-6edea51e421e4457ac0c3269f3be5157.jpg",
      ingredients: ["Spaghetti", "Pancetta", "Eggs", "Parmesan", "Black Pepper"],
    },
    {
      id: 4,
      title: "Cheeseburger",
      description: "Juicy beef patty with melted cheese, served with fries.",
      image: "https://s23209.pcdn.co/wp-content/uploads/2022/07/220602_DD_The-Best-Ever-Cheeseburger_267.jpg",
      ingredients: ["Beef Patty", "Cheddar Cheese", "Bun", "Lettuce", "Tomato"],
    },
    {
      id: 5,
      title: "Grilled Salmon",
      description: "Tender salmon fillet served with asparagus and a lemon butter sauce.",
      image: "https://www.dinneratthezoo.com/wp-content/uploads/2019/05/grilled-salmon-final-2.jpg",
      ingredients: ["Salmon", "Asparagus", "Butter", "Lemon", "Garlic"],
    },
    {
      id: 6,
      title: "Beef Tacos",
      description: "Seasoned beef served in soft tortillas with salsa and guacamole.",
      image: "https://loveandgoodstuff.com/wp-content/uploads/2020/08/classic-ground-beef-tacos-1200x1200.jpg",
      ingredients: ["Beef", "Tortillas", "Salsa", "Guacamole", "Lettuce"],
    },
    {
      id: 7,
      title: "Caesar Salad",
      description: "Romaine lettuce with croutons, parmesan, and Caesar dressing.",
      image: "https://natashaskitchen.com/wp-content/uploads/2019/01/Caesar-Salad-Recipe-3.jpg",
      ingredients: ["Romaine", "Croutons", "Parmesan", "Caesar Dressing"],
    },
    {
      id: 8,
      title: "Chicken Curry",
      description: "Spicy chicken curry served with steamed rice.",
      image: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Instant-Pot-Chicken-Curry-Recipe.jpg",
      ingredients: ["Chicken", "Curry Sauce", "Rice", "Spices", "Cilantro"],
    },
    {
      id: 9,
      title: "Vegetable Stir-Fry",
      description: "Fresh vegetables stir-fried in a savory soy sauce.",
      image: "https://natashaskitchen.com/wp-content/uploads/2020/08/Vegetable-Stir-Fry-2.jpg",
      ingredients: ["Broccoli", "Carrots", "Bell Peppers", "Soy Sauce", "Garlic"],
    },
    {
      id: 10,
      title: "BBQ Ribs",
      description: "Tender pork ribs glazed with a smoky BBQ sauce.",
      image: "https://www.southernliving.com/thmb/EUvJGe0PGPysUyWij6KmOZo7VWY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/oven-baked-baby-back-ribs-beauty-332_preview-34579f7f15ed4548ae3bb5b2048aab60.jpg",
      ingredients: ["Pork Ribs", "BBQ Sauce", "Spices", "Coleslaw"],
    },
    {
      id: 11,
      title: "Chicken Alfredo",
      description: "Creamy Alfredo sauce over fettuccine pasta with grilled chicken.",
      image: "https://www.budgetbytes.com/wp-content/uploads/2022/07/Chicken-Alfredo-bowl.jpg",
      ingredients: ["Fettuccine", "Chicken", "Cream", "Parmesan", "Garlic"],
    },
    {
      id: 12,
      title: "Chocolate Lava Cake",
      description: "Warm chocolate cake with a gooey molten center.",
      image: "https://www.foodandwine.com/thmb/XdFd-DvTtouryLCjeCqwhfmmK-A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/molten-chocolate-cake-FT-RECIPE0220-0a33d7d0ab0c45588f7bfe742d33a9bc.jpg",
      ingredients: ["Chocolate", "Butter", "Sugar", "Eggs", "Flour"],
    },
  ];
  