export const menuItems: FoodItem[] = [
    {
      id: 1,
      title: "Grilled Chicken Salad",
      description: "Fresh greens topped with grilled chicken and a light vinaigrette.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Chicken", "Lettuce", "Tomatoes", "Vinaigrette", "Cucumber"],
    },
    {
      id: 2,
      title: "Margherita Pizza",
      description: "Classic pizza with fresh mozzarella, tomatoes, and basil.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Pizza Dough", "Tomatoes", "Mozzarella", "Basil"],
    },
    {
      id: 3,
      title: "Spaghetti Carbonara",
      description: "Rich and creamy pasta with pancetta and parmesan.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Spaghetti", "Pancetta", "Eggs", "Parmesan", "Black Pepper"],
    },
    {
      id: 4,
      title: "Cheeseburger",
      description: "Juicy beef patty with melted cheese, served with fries.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Beef Patty", "Cheddar Cheese", "Bun", "Lettuce", "Tomato"],
    },
    {
      id: 5,
      title: "Grilled Salmon",
      description: "Tender salmon fillet served with asparagus and a lemon butter sauce.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Salmon", "Asparagus", "Butter", "Lemon", "Garlic"],
    },
    {
      id: 6,
      title: "Beef Tacos",
      description: "Seasoned beef served in soft tortillas with salsa and guacamole.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Beef", "Tortillas", "Salsa", "Guacamole", "Lettuce"],
    },
    {
      id: 7,
      title: "Caesar Salad",
      description: "Romaine lettuce with croutons, parmesan, and Caesar dressing.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Romaine", "Croutons", "Parmesan", "Caesar Dressing"],
    },
    {
      id: 8,
      title: "Chicken Curry",
      description: "Spicy chicken curry served with steamed rice.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Chicken", "Curry Sauce", "Rice", "Spices", "Cilantro"],
    },
    {
      id: 9,
      title: "Vegetable Stir-Fry",
      description: "Fresh vegetables stir-fried in a savory soy sauce.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Broccoli", "Carrots", "Bell Peppers", "Soy Sauce", "Garlic"],
    },
    {
      id: 10,
      title: "BBQ Ribs",
      description: "Tender pork ribs glazed with a smoky BBQ sauce.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Pork Ribs", "BBQ Sauce", "Spices", "Coleslaw"],
    },
    {
      id: 11,
      title: "Chicken Alfredo",
      description: "Creamy Alfredo sauce over fettuccine pasta with grilled chicken.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Fettuccine", "Chicken", "Cream", "Parmesan", "Garlic"],
    },
    {
      id: 12,
      title: "Chocolate Lava Cake",
      description: "Warm chocolate cake with a gooey molten center.",
      image: "/placeholder.svg?height=200&width=200",
      ingredients: ["Chocolate", "Butter", "Sugar", "Eggs", "Flour"],
    },
  ];
  